name: Create Artifact

on:
  schedule:
    - cron: 0 0 */14 * *
  push:
    branches:
      - master
    paths:
      - "**"
  pull_request:
    paths:
      - "**"
  workflow_dispatch:

jobs:
  deploy_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Script
        run: sudo ./setup.sh raspberrypi pi raspberry

      - uses: actions/upload-artifact@v3
        with:
          path: ./*.img
          if-no-files-found: error